### PR TITLE
feat: add transparent variant & update whiskers to 2.4.0

### PR DESCRIPTION
**Pull request by uncenter**
Supersedes #4.

### CODE REVIEW

**Comment by uncenter** [comment]
@duganchen would you mind testing this to make sure it works?

**Comment by duganchen** [comment]
image

It does not.

**Comment by duganchen** [comment]
Just gave your catppuccin-mocha-transparent a proper test and yes, it work well! :D

**Comment by uncenter** [comment]
Sweet! What did you have to change to get it working?

**Comment by duganchen** [comment]
Well, this is embarrassing, but I guess I have to answer. I had to test "catppuccin-mocha-transparent.micro" and not "catppuccin-mocha.micro."

**Comment by uncenter** [comment]
Ahaha no worries at all. Thanks for testing! Just wanted to make sure it wasn't something we had to mention in the README FAQ.

**Review by sgoudham — APPROVED** [review]

**Pull request merged**
